using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Misp
{

    [JsonObject]
    public class Org
    {
        /// <summary>
        /// The id is a human-readable identifier generated by the instance and used as reference in the event.
        /// </summary>
        [JsonProperty("id"), JsonRequired]
        public String Id { get; set; }

        /// <summary>
        /// The name is a readable description of the organization
        /// </summary>
        [JsonProperty("name"), JsonRequired]
        public String Name { get; set; }

        /// <summary>
        /// The uuid represents the Universally Unique IDentifier (UUID) [@!RFC4122] of the organization. The organization UUID is globally assigned to an organization and SHALL be kept overtime.
        /// </summary>
        [JsonProperty("uuid"), JsonRequired]
        public Guid UUID { get; set; }
    }
}
